# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: csv_to_xml_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'csv_to_xml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63sv_to_xml_service.proto\x12\x12\x63sv_to_xml_service\"2\n\x1d\x43onvertCsvToXmlAndSaveRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"B\n\x1e\x43onvertCsvToXmlAndSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x92\x01\n\x0f\x43svToXmlService\x12\x7f\n\x16\x43onvertCsvToXmlAndSave\x12\x31.csv_to_xml_service.ConvertCsvToXmlAndSaveRequest\x1a\x32.csv_to_xml_service.ConvertCsvToXmlAndSaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csv_to_xml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTCSVTOXMLANDSAVEREQUEST']._serialized_start=48
  _globals['_CONVERTCSVTOXMLANDSAVEREQUEST']._serialized_end=98
  _globals['_CONVERTCSVTOXMLANDSAVERESPONSE']._serialized_start=100
  _globals['_CONVERTCSVTOXMLANDSAVERESPONSE']._serialized_end=166
  _globals['_CSVTOXMLSERVICE']._serialized_start=169
  _globals['_CSVTOXMLSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
