# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import csv_to_xml_service_pb2 as csv__to__xml__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in csv_to_xml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CsvToXmlServiceStub(object):
    """Serviço para conversão
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertCsvToXmlAndSave = channel.unary_unary(
                '/csv_to_xml_service.CsvToXmlService/ConvertCsvToXmlAndSave',
                request_serializer=csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveRequest.SerializeToString,
                response_deserializer=csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveResponse.FromString,
                _registered_method=True)


class CsvToXmlServiceServicer(object):
    """Serviço para conversão
    """

    def ConvertCsvToXmlAndSave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CsvToXmlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertCsvToXmlAndSave': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertCsvToXmlAndSave,
                    request_deserializer=csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveRequest.FromString,
                    response_serializer=csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csv_to_xml_service.CsvToXmlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csv_to_xml_service.CsvToXmlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CsvToXmlService(object):
    """Serviço para conversão
    """

    @staticmethod
    def ConvertCsvToXmlAndSave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csv_to_xml_service.CsvToXmlService/ConvertCsvToXmlAndSave',
            csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveRequest.SerializeToString,
            csv__to__xml__service__pb2.ConvertCsvToXmlAndSaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
