# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_conversion_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_conversion_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66ile_conversion_service.proto\x12\x0fserver_services\"1\n\x1c\x43onvertCsvToDbAndSaveRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"A\n\x1d\x43onvertCsvToDbAndSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8f\x01\n\x15\x46ileConversionService\x12v\n\x15\x43onvertCsvToDbAndSave\x12-.server_services.ConvertCsvToDbAndSaveRequest\x1a..server_services.ConvertCsvToDbAndSaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_conversion_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTCSVTODBANDSAVEREQUEST']._serialized_start=50
  _globals['_CONVERTCSVTODBANDSAVEREQUEST']._serialized_end=99
  _globals['_CONVERTCSVTODBANDSAVERESPONSE']._serialized_start=101
  _globals['_CONVERTCSVTODBANDSAVERESPONSE']._serialized_end=166
  _globals['_FILECONVERSIONSERVICE']._serialized_start=169
  _globals['_FILECONVERSIONSERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
