# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pesquisa_texto_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pesquisa_texto_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpesquisa_texto_service.proto\x12\x0epesquisa_texto\"\x1d\n\x0c\x42uscaRequest\x12\r\n\x05termo\x18\x01 \x01(\t\"#\n\rBuscaResponse\x12\x12\n\nresultados\x18\x01 \x03(\t2b\n\x14PesquisaTextoService\x12J\n\x0b\x42uscarTexto\x12\x1c.pesquisa_texto.BuscaRequest\x1a\x1d.pesquisa_texto.BuscaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pesquisa_texto_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSCAREQUEST']._serialized_start=48
  _globals['_BUSCAREQUEST']._serialized_end=77
  _globals['_BUSCARESPONSE']._serialized_start=79
  _globals['_BUSCARESPONSE']._serialized_end=114
  _globals['_PESQUISATEXTOSERVICE']._serialized_start=116
  _globals['_PESQUISATEXTOSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
