# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import validate_schema_service_pb2 as validate__schema__service__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in validate_schema_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValidateSchemaServiceStub(object):
    """Define o serviço de validação de schema
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/validate_schema_service.ValidateSchemaService/Validate',
                request_serializer=validate__schema__service__pb2.ValidateRequest.SerializeToString,
                response_deserializer=validate__schema__service__pb2.ValidateSchemaResponse.FromString,
                _registered_method=True)


class ValidateSchemaServiceServicer(object):
    """Define o serviço de validação de schema
    """

    def Validate(self, request, context):
        """Método para validar um XML contra um schema XSD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidateSchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=validate__schema__service__pb2.ValidateRequest.FromString,
                    response_serializer=validate__schema__service__pb2.ValidateSchemaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'validate_schema_service.ValidateSchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('validate_schema_service.ValidateSchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValidateSchemaService(object):
    """Define o serviço de validação de schema
    """

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validate_schema_service.ValidateSchemaService/Validate',
            validate__schema__service__pb2.ValidateRequest.SerializeToString,
            validate__schema__service__pb2.ValidateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
