# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: validate_schema_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'validate_schema_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvalidate_schema_service.proto\x12\x17validate_schema_service\"&\n\x0fValidateRequest\x12\x13\n\x0bxsd_content\x18\x01 \x01(\t\"A\n\x16ValidateSchemaResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2~\n\x15ValidateSchemaService\x12\x65\n\x08Validate\x12(.validate_schema_service.ValidateRequest\x1a/.validate_schema_service.ValidateSchemaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'validate_schema_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEREQUEST']._serialized_start=58
  _globals['_VALIDATEREQUEST']._serialized_end=96
  _globals['_VALIDATESCHEMARESPONSE']._serialized_start=98
  _globals['_VALIDATESCHEMARESPONSE']._serialized_end=163
  _globals['_VALIDATESCHEMASERVICE']._serialized_start=165
  _globals['_VALIDATESCHEMASERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
